on:
  push:
    branches:
      - "master"
      - "nix"

jobs:
  build-and-push-docker-images:
    uses: Discord-TTS/shared-workflows/.github/workflows/docker.yml@v1
    with:
      repo-name: test-repo
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
